print('-----TABUADA-----')
nn = int(input('Digite um valor: '))
print(f'{nn} x  1 = {nn*1} ')
print(f'{nn} x  2 = {nn*2} ')
print(f'{nn} x  3 = {nn*3} ')
print(f'{nn} x  4 = {nn*4} ')
print(f'{nn} x  5 = {nn*5} ')
print(f'{nn} x  6 = {nn*6} ')
print(f'{nn} x  7 = {nn*7} ')
print(f'{nn} x  8 = {nn*8} ')
print(f'{nn} x  9 = {nn*9} ')
print(f'{nn} x 10 = {nn*10} ')
print('-----FIM PROGAMA-----')